# Generated by Django 5.1.6 on 2025-05-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='drinks',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=255)),
                ('drink_type', models.CharField(max_length=255)),
                ('drink_image', models.ImageField(upload_to='drinks/')),
                ('drink_abv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink_producer', models.CharField(max_length=255)),
                ('drink_tasting_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='drink_trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_score', models.IntegerField()),
                ('trending_date', models.DateTimeField(auto_now_add=True)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovedrinks.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='drink_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('image_url', models.ImageField(upload_to='drinks/')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovedrinks.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='diary_entries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('image_url', models.ImageField(upload_to='drinks/')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovedrinks.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logged', models.IntegerField()),
                ('top_5_drinks', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
