# Generated by Django 5.1.6 on 2025-05-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary_entries',
            options={'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AlterModelOptions(
            name='drink_log',
            options={'verbose_name': 'Drink Log', 'verbose_name_plural': 'Drink Logs'},
        ),
        migrations.AlterModelOptions(
            name='drink_trending',
            options={'verbose_name': 'Drink Trending', 'verbose_name_plural': 'Drink Trending'},
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={'verbose_name': 'Drink', 'verbose_name_plural': 'Drinks'},
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='user_stats',
            options={'verbose_name': 'User Stat', 'verbose_name_plural': 'User Stats'},
        ),
    ]
