# Generated by Django 5.1.6 on 2025-05-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0002_alter_diary_entries_options_alter_drink_log_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink_log',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='diary_entries',
        ),
    ]
