# Generated by Django 5.1.6 on 2025-05-10 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0003_remove_drink_log_image_url_delete_diary_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drink_log',
            new_name='DrinkLog',
        ),
    ]
