# Generated by Django 5.1.6 on 2025-05-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0004_rename_drink_log_drinklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_stats',
            name='top_5_drinks',
        ),
        migrations.AddField(
            model_name='user_stats',
            name='top_drink_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_drink_1', to='lovedrinks.drinks'),
        ),
        migrations.AddField(
            model_name='user_stats',
            name='top_drink_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_drink_2', to='lovedrinks.drinks'),
        ),
        migrations.AddField(
            model_name='user_stats',
            name='top_drink_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_drink_3', to='lovedrinks.drinks'),
        ),
        migrations.AddField(
            model_name='user_stats',
            name='top_drink_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_drink_4', to='lovedrinks.drinks'),
        ),
        migrations.AddField(
            model_name='user_stats',
            name='top_drink_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_drink_5', to='lovedrinks.drinks'),
        ),
    ]
