# Generated by Django 5.1.6 on 2025-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0006_remove_user_stats_total_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='drink_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
