# Generated by Django 5.1.6 on 2025-05-11 11:45

import django.core.validators
import lovedrinks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovedrinks', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), lovedrinks.models.validate_file_size]),
        ),
    ]
